2023-05-21 11:41:28,184 INFO <module>(51) INIT LOGGER SUCCESSED
2023-05-21 11:41:28,184 INFO <module>(51) INIT LOGGER SUCCESSED
2023-05-21 11:41:28,186 INFO <module>(51) INIT LOGGER SUCCESSED
2023-05-21 11:41:28,186 INFO <module>(51) INIT LOGGER SUCCESSED
2023-05-21 11:41:37,763 INFO <module>(51) INIT LOGGER SUCCESSED
2023-05-21 11:41:37,763 INFO <module>(51) INIT LOGGER SUCCESSED
2023-05-21 11:41:37,778 INFO <module>(51) INIT LOGGER SUCCESSED
2023-05-21 11:41:37,864 INFO <module>(51) INIT LOGGER SUCCESSED
2023-05-21 11:42:12,074 INFO get_all(78) executing query: SELECT * FROM THANHVIEN
2023-05-21 11:48:13,951 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:48:13,956 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:48:13,958 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:48:13,959 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:48:54,665 INFO insert(54) executing query: Insert into NGHENGHIEP (TENNGHENGHIEP) values ("Coder")
2023-05-21 11:49:19,970 INFO get_all(42) executing query: SELECT * FROM NGHENGHIEP
2023-05-21 11:49:19,974 ERROR get_all(47) Cannot execute query: SELECT * FROM NGHENGHIEP
2023-05-21 11:49:19,975 ERROR get_all(48) 'id'
Traceback (most recent call last):
  File "/app/src/models/job.py", line 45, in get_all
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 45, in <listcomp>
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 20, in from_json
    _json["id"],
KeyError: 'id'
2023-05-21 11:50:31,760 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:50:31,760 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:50:31,775 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:50:31,800 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:50:33,951 INFO get_all(42) executing query: SELECT * FROM NGHENGHIEP
2023-05-21 11:50:33,964 ERROR get_all(48) Cannot execute query: SELECT * FROM NGHENGHIEP
2023-05-21 11:50:33,965 ERROR get_all(49) (2003, "Can't connect to MySQL server on 'se_mysql' ([Errno 111] Connection refused)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 616, in connect
    sock = socket.create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/models/job.py", line 44, in get_all
    _, jobs = exec_query(query, mode="fetchall")
  File "/app/src/utils/db_helper.py", line 19, in exec_query
    with get_connection() as connection:
  File "/app/src/utils/db_helper.py", line 8, in get_connection
    connection = pymysql.connect(
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 668, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'se_mysql' ([Errno 111] Connection refused)")
2023-05-21 11:51:17,885 INFO get_all(42) executing query: SELECT * FROM NGHENGHIEP
2023-05-21 11:51:41,382 INFO insert(55) executing query: Insert into NGHENGHIEP (TENNGHENGHIEP) values ("Coder")
2023-05-21 11:51:54,306 INFO get_all(42) executing query: SELECT * FROM NGHENGHIEP
2023-05-21 11:51:54,309 ERROR get_all(48) Cannot execute query: SELECT * FROM NGHENGHIEP
2023-05-21 11:51:54,309 ERROR get_all(49) 'id'
Traceback (most recent call last):
  File "/app/src/models/job.py", line 46, in get_all
    except Exception as err:
  File "/app/src/models/job.py", line 46, in <listcomp>
    except Exception as err:
  File "/app/src/models/job.py", line 20, in from_json
    _json["id"],
KeyError: 'id'
2023-05-21 11:57:57,950 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:57:57,950 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:57:57,950 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 11:57:57,950 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:00:39,969 INFO insert(54) executing query: Insert into NGHENGHIEP (TENNGHENGHIEP) values ("Coder")
2023-05-21 12:00:58,674 INFO get_all(42) executing query: SELECT * FROM NGHENGHIEP
2023-05-21 12:00:58,677 ERROR get_all(47) Cannot execute query: SELECT * FROM NGHENGHIEP
2023-05-21 12:00:58,677 ERROR get_all(48) Job() takes no arguments
Traceback (most recent call last):
  File "/app/src/models/job.py", line 45, in get_all
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 45, in <listcomp>
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 19, in from_json
    return Job(
TypeError: Job() takes no arguments
2023-05-21 12:01:00,989 INFO get_all(42) executing query: SELECT * FROM NGHENGHIEP
2023-05-21 12:01:00,992 ERROR get_all(47) Cannot execute query: SELECT * FROM NGHENGHIEP
2023-05-21 12:01:00,992 ERROR get_all(48) Job() takes no arguments
Traceback (most recent call last):
  File "/app/src/models/job.py", line 45, in get_all
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 45, in <listcomp>
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 19, in from_json
    return Job(
TypeError: Job() takes no arguments
2023-05-21 12:02:21,043 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:02:21,044 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:02:21,062 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:02:21,077 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:02:23,090 INFO insert(54) executing query: Insert into NGHENGHIEP (TENNGHENGHIEP) values ("Coder")
2023-05-21 12:02:23,099 ERROR insert(59) Cannot execute query: Insert into NGHENGHIEP (TENNGHENGHIEP) values ("Coder")
2023-05-21 12:02:23,099 ERROR insert(60) (2003, "Can't connect to MySQL server on 'se_mysql' ([Errno 111] Connection refused)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 616, in connect
    sock = socket.create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/models/job.py", line 56, in insert
    exec_query(query)
  File "/app/src/utils/db_helper.py", line 19, in exec_query
    with get_connection() as connection:
  File "/app/src/utils/db_helper.py", line 8, in get_connection
    connection = pymysql.connect(
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 668, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'se_mysql' ([Errno 111] Connection refused)")
2023-05-21 12:02:30,083 INFO insert(54) executing query: Insert into NGHENGHIEP (TENNGHENGHIEP) values ("Coder")
2023-05-21 12:02:44,796 INFO get_all(42) executing query: SELECT * FROM NGHENGHIEP
2023-05-21 12:02:44,799 ERROR get_all(47) Cannot execute query: SELECT * FROM NGHENGHIEP
2023-05-21 12:02:44,799 ERROR get_all(48) Job() takes no arguments
Traceback (most recent call last):
  File "/app/src/models/job.py", line 45, in get_all
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 45, in <listcomp>
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 19, in from_json
    return Job(
TypeError: Job() takes no arguments
2023-05-21 12:03:33,428 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:03:33,428 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:03:33,455 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:03:33,461 INFO <module>(62) INIT LOGGER SUCCESSED
2023-05-21 12:04:00,957 INFO insert(53) executing query: Insert into NGHENGHIEP (TENNGHENGHIEP) values ("Coder")
2023-05-21 12:04:05,719 INFO get_all(41) executing query: SELECT * FROM NGHENGHIEP
2023-05-21 12:04:05,722 ERROR get_all(46) Cannot execute query: SELECT * FROM NGHENGHIEP
2023-05-21 12:04:05,723 ERROR get_all(47) Job() takes no arguments
Traceback (most recent call last):
  File "/app/src/models/job.py", line 44, in get_all
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 44, in <listcomp>
    return None, [Job.from_json(p) for p in jobs]
  File "/app/src/models/job.py", line 21, in from_json
    return Job(id=_json["MANGHENGHIEP"], name=_json["TENNGHENGHIEP"])
TypeError: Job() takes no arguments
